#!/usr/bin/python
import numpy as np
import os

from grepen import *
from dos import *
from poscar import *
from charge import *

Aposcar=poscar()
Agrepen=grepen()
Ados=dos(Agrepen)
Acharge = charge(Aposcar,Agrepen,Ados)

