#!/usr/bin/python
import numpy as np
import os

from grepen import *
from dos import *
from bands import *
from errors import *

dirA = raw_input('input A directory name: ')
dirB = raw_input('input B directory name, same to skip: ')
#dirA_md5 = os.popen("find "+dirA+" -type f -name 'INCAR' -o -name 'OUTCAR' -exec md5sum {} + | awk '{print $1}' | sort | md5sum | awk '{print $1}'").read()
#dirB_md5 = os.popen("find "+dirB+" -type f -name 'INCAR' -o -name 'OUTCAR' -exec md5sum {} + | awk '{print $1}' | sort | md5sum | awk '{print $1}'").read()
#dirB_md5 = os.popen("find "+os.path.dirname(os.path.abspath(__file__))+" -type f -name '*.py' -exec md5sum {} + | awk '{print $1}' | sort | md5sum | awk '{print $1}'").read()
#from logging import *
#sys.stdout = Logger('.'+os.path.basename(__file__)+'.'+dirA_md5+'.'+dirB_md5)

os.chdir(dirA)
Agrepen=grepen()
Ados=dos(Agrepen)
Abands=bands(Agrepen)

if dirA != dirB:
    os.chdir('..')
    os.chdir(dirB)
    Bgrepen=grepen()
    Bdos=dos(Bgrepen)
    Bbands=bands(Bgrepen)
else:
    Bgrepen=Agrepen
    Bdos=Ados
    Bbands=Abands

ABerrors=errors(Agrepen,Ados,Abands,Bgrepen,Bdos,Bbands,dirA,dirB)
